export enum SettingsActionTypes {
  GET_SETTINGS = 'GET_SETTINGS',
  GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS',
  GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE',

  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
  UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS',
  UPDATE_SETTINGS_FAILURE = 'UPDATE_SETTINGS_FAILURE',
}
