export enum WalletActionTypes {
  GET_WALLETS = 'GET_WALLETS',
  GET_WALLETS_SUCCESS = 'GET_WALLETS_SUCCESS',
  GET_WALLETS_FAILURE = 'GET_WALLETS_FAILURE',

  ADD_SIGNER = 'ADD_SIGNER',
  ADD_SIGNER_SUCCESS = 'ADD_SIGNER_SUCCESS',
  ADD_SIGNER_FAILURE = 'ADD_SIGNER_FAILURE',

  CHANGE_WALLET = 'CHANGE_WALLET',

  SIGN_PSBT = 'SIGN_PSBT',
  SIGN_PSBT_SUCCESS = 'SIGN_PSBT_SUCCESS',
  SIGN_PSBT_FAILURE = 'SIGN_PSBT_FAILURE',

  BROADCAST_TRANSACTION = 'BROADCAST_TRANSACTION',
  BROADCAST_TRANSACTION_SUCCESS = 'BROADCAST_TRANSACTION_SUCCESS',
  BROADCAST_TRANSACTION_FAILURE = 'BROADCAST_TRANSACTION_FAILURE',
}