export enum WalletActionTypes {
  GET_WALLETS = 'GET_WALLETS',
  GET_WALLETS_SUCCESS = 'GET_WALLETS_SUCCESS',
  GET_WALLETS_FAILURE = 'GET_WALLETS_FAILURE',

  ADD_SIGNER = 'ADD_SIGNER',
  ADD_SIGNER_SUCCESS = 'ADD_SIGNER_SUCCESS',
  ADD_SIGNER_FAILURE = 'ADD_SIGNER_FAILURE',

  CHANGE_WALLET = 'CHANGE_WALLET',
}
