export enum DeviceActionTypes {
  GET_DEVICES = 'GET_DEVICES',
  GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS',
  GET_DEVICES_FAILURE = 'GET_DEVICES_FAILURE',

  SCAN_DEVICES_START = 'SCAN_DEVICES_START',
  SCAN_DEVICES_STOP = 'SCAN_DEVICES_STOP',
}
